# Required metadata
sonar.projectKey=lc2410_stock-market-predictor
sonar.organization=lc2410

# Project information
sonar.sources=backend, frontend
sonar.exclusions=backend/tests/**, frontend/tests/**, frontend/styles/**, frontend/index.html

# Excluding certain files from coverage analysis
sonar.coverage.exclusions=frontend/**, **/download_sentiment_analysis_pretrained_model.py

# Python-specific settings
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.10