# Required metadata
sonar.projectKey=lc2410_stock-market-predictor
sonar.organization=lc2410

# Project information
sonar.sources=backend, frontend, app.py
sonar.exclusions=backend/tests/**, frontend/tests/**, frontend/styles/**, frontend/index.html

# Exclude frontend from the line-by-line coverage math
sonar.coverage.exclusions=frontend/**

# Python-specific settings
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.10