/*
 * headlines.sql
 * 
 * This DDL script defines the 'headlines' table which stores cached market news articles, 
 * including titles, publishers, links, summaries, and publication dates.
 */
CREATE TABLE headlines (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(4000),
    publisher VARCHAR2(4000),
    link VARCHAR2(4000),
    summary VARCHAR2(4000),
    published_at TIMESTAMP
);
