name: Daily Database Update

on:
  schedule:
    - cron: '30 21 * * 1-5'
  workflow_dispatch:

jobs:
  update-database:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Remote Update via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DSN: ${{ secrets.DB_DSN }}
          DB_WALLET_BASE64: ${{ secrets.DB_WALLET_BASE64 }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: DB_USER,DB_PASSWORD,DB_DSN,DB_WALLET_BASE64
          script: |
            set -e
            cd /home/ubuntu/stock-market-predictor
            echo "$DB_WALLET_BASE64" | base64 -d > /home/ubuntu/wallet.zip
            mkdir -p /home/ubuntu/wallet
            python3 -m zipfile -e /home/ubuntu/wallet.zip /home/ubuntu/wallet
            sed -i "s|?/network/admin|/home/ubuntu/wallet|g" /home/ubuntu/wallet/sqlnet.ora


            source venv/bin/activate
            export TNS_ADMIN=/home/ubuntu/wallet

            echo "Starting daily database update on remote server..."
            PYTHONPATH=backend python backend/database/scripts/update_db.py
            echo "Database update completed successfully."
